import Head from "next/head";
import React from "react";

interface LayoutI {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutI) {
  return (
    <>
      <Head>
        <title>Resumint</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-5 flex min-h-screen flex-col p-5">{children}</main>
    </>
  );
}
